name: neuroinsight
description: "A new Flutter project."

publish_to:

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter



  #image picker
  image_picker: ^1.0.7
  file_picker: ^8.0.0+1
  pdf: ^3.11.3
  printing: ^5.12.0
  path_provider: ^2.1.3


  #huge icons
  hugeicons: ^0.0.11

  #splash screen
  introduction_screen: ^3.1.12

  #scrollable picker
  numberpicker: ^2.1.2
  carousel_slider: ^5.1.1
  percent_indicator: ^4.2.3
  
  # for auth and firestore
  firebase_storage: ^11.7.7
  async: ^2.11.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.3
  uuid: ^4.5.1

  #google_maps_flutter
  google_maps_flutter: ^2.12.3
  url_launcher: ^6.3.2
  location: ^6.0.2
  http: ^1.2.1
  intl: ^0.19.0

  #calender
  table_calendar: ^3.1.2
  collection: ^1.18.0

  # For the Google logo icon
  font_awesome_flutter: ^10.7.0

  #google fonts lora
  google_fonts: ^6.2.1

  #animations
  lottie: ^3.1.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/animations/
    - assets/animations/a.json


