// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqOe-vzaSx2ZkZL9MDapwfoDa5iBvX4e8',
    appId: '1:59493945297:web:4416f102b4c6fd30aedaf0',
    messagingSenderId: '59493945297',
    projectId: 'samnandha8772',
    authDomain: 'samnandha8772.firebaseapp.com',
    storageBucket: 'samnandha8772.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6XjbrVVj-AGRRGfbLTP6Q37_NkAZ92nE',
    appId: '1:59493945297:android:973818f48d921793aedaf0',
    messagingSenderId: '59493945297',
    projectId: 'samnandha8772',
    storageBucket: 'samnandha8772.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5dPT7pimCUbQmkMfY1prtiq6epUtxZ9Q',
    appId: '1:59493945297:ios:a1358571f417de39aedaf0',
    messagingSenderId: '59493945297',
    projectId: 'samnandha8772',
    storageBucket: 'samnandha8772.firebasestorage.app',
    iosClientId: '59493945297-4rngo9c20og6mg67miuaotig1g1bp5i7.apps.googleusercontent.com',
    iosBundleId: 'com.example.neuroinsight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5dPT7pimCUbQmkMfY1prtiq6epUtxZ9Q',
    appId: '1:59493945297:ios:a1358571f417de39aedaf0',
    messagingSenderId: '59493945297',
    projectId: 'samnandha8772',
    storageBucket: 'samnandha8772.firebasestorage.app',
    iosClientId: '59493945297-4rngo9c20og6mg67miuaotig1g1bp5i7.apps.googleusercontent.com',
    iosBundleId: 'com.example.neuroinsight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqOe-vzaSx2ZkZL9MDapwfoDa5iBvX4e8',
    appId: '1:59493945297:web:ceea50a86344017faedaf0',
    messagingSenderId: '59493945297',
    projectId: 'samnandha8772',
    authDomain: 'samnandha8772.firebaseapp.com',
    storageBucket: 'samnandha8772.firebasestorage.app',
  );
}
